
export * from './WidgetPartnerIntro';
export * from './WidgetCompanyProfile';
export * from './WidgetNetworkStats';
export * from './WidgetSynergy';
export * from './WidgetContactDetails';
export * from './WidgetSourceChannel';
export * from './WidgetFallback';
export * from './WidgetBrand';
export * from './WidgetCatalog';
export * from './WidgetSourcing';
export * from './WidgetVolume';
export * from './WidgetOrderSize';
export * from './WidgetDestination';
export * from './WidgetExperience';
export * from './WidgetReferences';
export * from './WidgetBudget';
export * from './WidgetWhatsApp';
export * from './WidgetIdentity';
